ALTER TABLE public.transporte_content
  ADD COLUMN IF NOT EXISTS how_it_works_title text DEFAULT 'Como funciona',
  ADD COLUMN IF NOT EXISTS how_it_works_subtitle text DEFAULT 'Simples, rápido e seguro do começo ao fim',
  ADD COLUMN IF NOT EXISTS step_1_title text DEFAULT 'Agendamento',
  ADD COLUMN IF NOT EXISTS step_1_text text DEFAULT 'Você fala com a gente pelo WhatsApp e combina o melhor dia e horário.',
  ADD COLUMN IF NOT EXISTS step_2_title text DEFAULT 'Buscamos seu pet',
  ADD COLUMN IF NOT EXISTS step_2_text text DEFAULT 'Tio João vai até a sua casa, no horário marcado, com todo o cuidado.',
  ADD COLUMN IF NOT EXISTS step_3_title text DEFAULT 'Cuidado no Le Ville Pet',
  ADD COLUMN IF NOT EXISTS step_3_text text DEFAULT 'Seu pet recebe nossos serviços com carinho e atenção individual.',
  ADD COLUMN IF NOT EXISTS step_4_title text DEFAULT 'Levamos de volta',
  ADD COLUMN IF NOT EXISTS step_4_text text DEFAULT 'Após o atendimento, devolvemos seu pet em segurança na sua porta.',
  ADD COLUMN IF NOT EXISTS coverage_title text DEFAULT 'Onde atendemos',
  ADD COLUMN IF NOT EXISTS coverage_text text DEFAULT 'Nosso transporte atende toda a região do Villaggio Mall Center, em Bauru-SP, e bairros próximos. Consulte disponibilidade para a sua região pelo WhatsApp.',
  ADD COLUMN IF NOT EXISTS coverage_neighborhoods text DEFAULT 'Vila Aviação · Jardim Estoril · Vila Cardia · Jardim Nasrala · Centro · Jardim Marambá · Jardim Auri Verde',
  ADD COLUMN IF NOT EXISTS safety_title text DEFAULT 'Segurança em primeiro lugar',
  ADD COLUMN IF NOT EXISTS safety_text text DEFAULT 'O veículo é higienizado a cada transporte e equipado com ar condicionado, ventilação adequada e contenção segura para que seu pet viaje confortável e protegido. Tio João tem experiência no manejo de cães e gatos de todos os portes.',
  ADD COLUMN IF NOT EXISTS pricing_title text DEFAULT 'Quanto custa',
  ADD COLUMN IF NOT EXISTS pricing_text text DEFAULT 'O valor varia conforme a distância e a frequência. Consulte um orçamento personalizado pelo WhatsApp — temos condições especiais para clientes recorrentes do hotelzinho e banho & tosa.',
  ADD COLUMN IF NOT EXISTS faq_title text DEFAULT 'Perguntas Frequentes',
  ADD COLUMN IF NOT EXISTS faq_q1 text DEFAULT 'Preciso ter caixa de transporte?',
  ADD COLUMN IF NOT EXISTS faq_a1 text DEFAULT 'Não é obrigatório. Temos caixas adequadas no veículo, mas se você preferir usar a sua, sem problema.',
  ADD COLUMN IF NOT EXISTS faq_q2 text DEFAULT 'Vocês atendem gatos também?',
  ADD COLUMN IF NOT EXISTS faq_a2 text DEFAULT 'Sim! Cães e gatos de todos os portes são bem-vindos.',
  ADD COLUMN IF NOT EXISTS faq_q3 text DEFAULT 'Como funciona o pagamento?',
  ADD COLUMN IF NOT EXISTS faq_a3 text DEFAULT 'O transporte é cobrado junto com o serviço do Le Ville Pet. Aceitamos Pix, dinheiro e cartão.',
  ADD COLUMN IF NOT EXISTS faq_q4 text DEFAULT 'Posso acompanhar a viagem?',
  ADD COLUMN IF NOT EXISTS faq_a4 text DEFAULT 'Claro! Mantemos contato pelo WhatsApp do início ao fim do trajeto, com atualizações sempre que precisar.',
  ADD COLUMN IF NOT EXISTS testimonial_title text DEFAULT 'O que dizem sobre nós',
  ADD COLUMN IF NOT EXISTS testimonial_text text DEFAULT 'O Tio João é uma pessoa incrível! Confio totalmente nele para buscar minha cachorrinha. Sempre pontual, carinhoso e o veículo é impecável.',
  ADD COLUMN IF NOT EXISTS testimonial_author text DEFAULT 'Mariana — tutora da Mel';

-- Switch icons to lucide names
UPDATE public.transporte_content SET
  highlight_1_icon = 'Snowflake',
  highlight_2_icon = 'Shield',
  highlight_3_icon = 'Heart',
  highlight_4_icon = 'Clock',
  highlight_5_icon = 'MapPin',
  highlight_6_icon = 'PawPrint';