
ALTER TABLE public.site_config
  ADD COLUMN IF NOT EXISTS hero_highlight_word text DEFAULT 'melhor.',
  ADD COLUMN IF NOT EXISTS hero_btn_primary_text text DEFAULT '💬 Fale no WhatsApp',
  ADD COLUMN IF NOT EXISTS hero_btn_secondary_text text DEFAULT 'Conheça o Hotelzinho →',
  ADD COLUMN IF NOT EXISTS hero_stat_1_num text DEFAULT '500+',
  ADD COLUMN IF NOT EXISTS hero_stat_1_label text DEFAULT 'Pets Atendidos',
  ADD COLUMN IF NOT EXISTS hero_stat_2_num text DEFAULT '5★',
  ADD COLUMN IF NOT EXISTS hero_stat_2_label text DEFAULT 'Avaliação Google',
  ADD COLUMN IF NOT EXISTS hero_stat_3_num text DEFAULT '3+',
  ADD COLUMN IF NOT EXISTS hero_stat_3_label text DEFAULT 'Anos de Experiência',
  ADD COLUMN IF NOT EXISTS sobre_image_url text DEFAULT '',
  ADD COLUMN IF NOT EXISTS sobre_cta_text text DEFAULT 'Venha nos conhecer →',
  ADD COLUMN IF NOT EXISTS cta_hotel_title text DEFAULT 'Vai viajar? Deixe seu pet com a gente!',
  ADD COLUMN IF NOT EXISTS cta_hotel_text text DEFAULT 'Nosso hotelzinho oferece conforto, segurança e muito carinho enquanto você viaja tranquilo.',
  ADD COLUMN IF NOT EXISTS cta_hotel_btn1_text text DEFAULT '🐾 Conhecer Hotelzinho',
  ADD COLUMN IF NOT EXISTS cta_hotel_btn2_text text DEFAULT '💬 Agendar pelo WhatsApp',
  ADD COLUMN IF NOT EXISTS cta_hotel_image_url text DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_whatsapp_btn_text text DEFAULT 'Chamar no WhatsApp',
  ADD COLUMN IF NOT EXISTS contact_maps_btn_text text DEFAULT 'Ver no Mapa',
  ADD COLUMN IF NOT EXISTS contact_instagram_btn_text text DEFAULT 'Seguir',
  ADD COLUMN IF NOT EXISTS gallery_section_title text DEFAULT 'Momentos Especiais',
  ADD COLUMN IF NOT EXISTS gallery_section_subtitle text DEFAULT 'Os melhores momentos dos nossos pets',
  ADD COLUMN IF NOT EXISTS video_section_title text DEFAULT 'Em Destaque',
  ADD COLUMN IF NOT EXISTS video_section_subtitle text DEFAULT 'Assista aos nossos vídeos favoritos',
  ADD COLUMN IF NOT EXISTS footer_description text DEFAULT 'Cuidamos do seu pet com amor em Bauru-SP.',
  ADD COLUMN IF NOT EXISTS copyright_text text DEFAULT '© 2026 Le Ville Pet — Todos os direitos reservados.',
  ADD COLUMN IF NOT EXISTS instagram_handle text DEFAULT '@levillepetbauru',
  ADD COLUMN IF NOT EXISTS facebook_handle text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok_handle text DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube_handle text DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_btn_text text DEFAULT 'Seguir no Instagram',
  ADD COLUMN IF NOT EXISTS whatsapp_btn_text text DEFAULT 'Chamar no WhatsApp',
  ADD COLUMN IF NOT EXISTS facebook_btn_text text DEFAULT 'Curtir no Facebook',
  ADD COLUMN IF NOT EXISTS tiktok_btn_text text DEFAULT 'Seguir no TikTok',
  ADD COLUMN IF NOT EXISTS youtube_btn_text text DEFAULT 'Inscrever-se',
  ADD COLUMN IF NOT EXISTS faleconosco_title text DEFAULT 'Fale com o Le Ville Pet',
  ADD COLUMN IF NOT EXISTS faleconosco_subtitle text DEFAULT 'Estamos prontos para te atender',
  ADD COLUMN IF NOT EXISTS faleconosco_card_title text DEFAULT 'Chame no WhatsApp!',
  ADD COLUMN IF NOT EXISTS faleconosco_card_text text DEFAULT 'Tire suas dúvidas, agende serviços ou venha nos conhecer. Respondemos rapidinho!',
  ADD COLUMN IF NOT EXISTS faleconosco_btn_text text DEFAULT 'Abrir WhatsApp Agora',
  ADD COLUMN IF NOT EXISTS localizacao_title text DEFAULT 'Nossa Localização',
  ADD COLUMN IF NOT EXISTS localizacao_subtitle text DEFAULT 'Venha nos visitar em Bauru-SP',
  ADD COLUMN IF NOT EXISTS localizacao_maps_btn_text text DEFAULT 'Abrir no Google Maps',
  ADD COLUMN IF NOT EXISTS localizacao_route_btn_text text DEFAULT 'Calcular Rota',
  ADD COLUMN IF NOT EXISTS localizacao_howto_text text DEFAULT 'Estamos localizados no Villaggio Mall Center, com fácil acesso pela Av. Affonso José Aiello. Estacionamento gratuito disponível no local.';
